# -*- coding: utf-8 -*-
"""Poxko.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bq5OewfDK2SmiMZ0GKN7qJo4Kj0zTKM6
"""

!pip3 install ColabTurtle
from ColabTurtle.Turtle import *

initializeTurtle()
bgcolor('white')
pencolor('black')

penup()
goto(200, 300)
pendown()
color('red')
forward(200)
right(90)
speed(10)
for i in range(10):
  forward(17)
  right(20)

penup()
goto(300,300)
pendown()
color('blue')
speed(10)
for i in range(18):
    forward(17)
    right(20)

penup()
home()
goto(400,300)
pendown()
color('green')
right(30)
forward(100)
penup()
goto(400,213.97)
pendown()
right(120)
forward(100)

penup()
home()
goto(500,300)
pendown()
color('black')
forward(100)
backward(50)
goto(540,220)
goto(500,250)
goto(540,300)

penup()
home()
goto(600,300)
right(300)
pendown()
color('purple')
speed(10)
for i in range(18):
    forward(17)
    right(20)

penup()
home()
goto(700, 350)
pendown()
color('black')
right(90)
backward(500)
for i in range(70):
    forward(7)
    right(0.2)
speed(2)
left(18+180)
penup()
forward(300)
setheading(270)
write("Il mitico", align="center", font=(25, "Arial", "italic"))
color('rgb(70 110 70)')
backward(40)