# -*- coding: utf-8 -*-
"""Poxko.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bq5OewfDK2SmiMZ0GKN7qJo4Kj0zTKM6
"""

!pip3 install ColabTurtle
from ColabTurtle.Turtle import *

initializeTurtle()
bgcolor('white')
pencolor('black')

penup()
goto(200, 400)
pendown()
color('red')
forward(200)
right(90)
speed(10)
for i in range(10):
  forward(17)
  right(20)

penup()
goto(300,400)
pendown()
color('blue')
speed(10)
for i in range(18):
    forward(17)
    right(20)

penup()
home()
goto(400,400)
pendown()
color('green')
right(30)
forward(100)
penup()
goto(400,313.97)
pendown()
right(120)
forward(100)

penup()
home()
goto(500,400)
pendown()
color('black')
forward(100)
backward(50)
goto(540,320)
goto(500,350)
goto(540,400)

penup()
home()
goto(600,400)
right(300)
pendown()
color('purple')
speed(10)
for i in range(18):
    forward(17)
    right(20)