# -*- coding: utf-8 -*-
"""scritte turtle

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v4EcgBcw0hVreh3nCpx6UvJbXtVsX_JQ
"""

!pip3 install ColabTurtle
from ColabTurtle.Turtle import *

n = input("Inserisci la scritta: ")

initializeTurtle()
bgcolor('white')
pencolor('black')

speed(10)
nome = list(n)
nome

x=0
for j in range(0,len(nome)):
  penup()
  x += 130
  goto(x,300)
  pendown()
  if nome[j] == 'p':
    forward(200)
    right(90)
    speed(10)
    for i in range(10):
      forward(17)
      right(20)
    right(90)
  elif nome[j] == 'o':
    left(90)
    for i in range(18):
      forward(17)
      right(20)
    right(70)
  elif nome[j] == 'x':
    right(30)
    forward(100)
    backward(50)
    left(60)
    forward(50)
    backward(100)
    right(30)
  elif nome[j] == 'k':
    forward(100)
    backward(50)
    right(50)
    forward(45)
    backward(45)
    right(90)
    forward(60)
    backward(60)
    left(140)